### ISSUE TITLE
Wiki: Onboarding

### ISSUE THREAD

**Issue by thetanmancan** [hackforla/tdm-calculator#2263]
### Overview
We need a wiki that explains what team leads need to do when onboarding a new team member onto TDM.

### Action Items
- [x] Create a page for onboarding in the wiki.
- [x] Add a link to the created wiki page in the Resources section below.
- [x] Write documentation in the wiki for how to onboard new team members.

### Resources
- Wiki with a brief explanation to new team members of what happens during onboarding: [Joining the TDM Calculator Team](https://github.com/hackforla/tdm-calculator/wiki/Joining-the-TDM-Calculator--Team)
- #1618 
- New onboarding wiki created by this issue: https://github.com/hackforla/tdm-calculator/wiki/Onboarding-new-team-members

**Comment by shmonks** [comment]
I need someone familiar with TDM's onboarding processes to check this (especially re: onboarding developers: I presume they have to answer 'Yes' to everything on the onboarding test?) Also, I don't yet have access to TDM Figma so that section will need to be edited for accuracy. I'm currently unable to move this into another column.

**Comment by thetanmancan** [comment]
Hi @shmonks. I've moved this issue to the Questions/Clarifications column so that a PM can answer your question and hopefully address your GitHub and Figma woes.

**Comment by shmonks** [comment]
Thank you, @thetanmancan!

**Comment by ExperimentsInHonesty** [comment]
@shmonks 

> I presume they have to answer 'Yes' to everything on the onboarding test?) 

A: yes

>I've only included links for the main TDM Team Roster, and not the Collab Roster - should it be both?

A: just the main roster

>Also, I don't yet have access to TDM Figma so that section will need to be edited for accuracy. 

A: We will get you access to figma during todays PM  meeting, please add it to the agenda

>I'm currently unable to move this into the In Progress or Questions columns.

A: Sorry, we have fixed

**Comment by ExperimentsInHonesty** [comment]
@shmonks Do you need edit access for [TDM figma](https://www.figma.com/files/team/1043961321383537981/all-projects?fuid=775836858007206739), or is being able to see it sufficient

**Comment by shmonks** [comment]
The latter: being able to see is sufficient.

**Comment by shmonks** [comment]
I still don't have (visual) access to TDM Figma - it doesn't appear for me in the TDM 1Password vault or Google Drive. Could someone fix this for me so I can complete this issue?

**Comment by thetanmancan** [comment]
Hi @shmonks. I sent a Figma invitation to your email.
